name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@master
      - name: Run Django unit tests
        run: |
          pip3 install --user django
          python3 DJANGO/airline/manage.py test
