name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
        with:
            token: ${{ secrets.MY_SECRET_HARVARD_TEST }}
      - name: Run Django unit tests
        run: |
          python --version
