name: Testing
on: push


jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@HARVARD_COURSES
      - name: Run Django unit tests
        run: |
          python --version
          python3 --version