permissions:
  contents: read
name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
        with:
            token: ${{ secrets.MY_SECRET_HARVARD_TEST }}
      - name: Run Django unit tests
        run: |
          pip3 install --user django
          python3 DJANGO/airline/manage.py test
